### ISSUE TITLE
Meaning of paramenter_number_of_layer_list values

### ISSUE THREAD

**Issue by MarcCoru** [Wensi-Tang/OS-CNN#1]
Hi,
Thanks for your work, code and paper.
In https://github.com/Wensi-Tang/OS-CNN/blob/19193dd442cceed0fd8cef67a2e406129d15b756/Classifiers/OS_CNN/OS_CNN_easy_use.py#L23
you define the default `paramenter_number_of_layer_list` that is used in https://github.com/Wensi-Tang/OS-CNN/blob/master/1_1_OS-CNN_easy_use_Run_and_Save_Model.ipynb to train the model.

* Could you provide some detail on the meaning of values in `[8*128, 5*128*256 + 2*256*128]`?
* Did you use this specific setting for all the UCR datasets or did you vary this hyperparameter?

**Comment by Wensi-Tang** [comment]
Thank you for your attention! Below is our detailed response to your questions. 

#### 1.	**paramenter_number_of_layer_list** = [8\*128, 5\*128\*256 + 2\*256\*128]

**paramenter_number_of_layer_list** is used to define the number of parameter(NoP) for each layer of OS-CNN. 

The meaning of number in it is:

**paramenter_number_of_layer_list** = [**NoP_of_first_layer**, **NoP_of_second_layer**]

In our work, we keep the model size of OS-CNN similar to [FCN](https://arxiv.org/abs/1611.06455). The reason for that is we want a fair comparison. Hence, each layer's NoP of OS-CNN is expected to be equal to each layer's NoP of FCN. 

 
For example, the first layer of FCN has 128 channel and the kernel size is 8. Therefore, the first layer’s NoP is 8\*128 (we don’t calculate the bias term for simplicity). 
 
<details>
<summary>Click to expand the explanation of OS-CNN's NoP of the second layer</summary>

Someone might notice that the OS-CNN’s NoP of the second layer is 5\*128\*256 + 2\*256\*128, which is different from the FCN’s NoP of the second layer 5\*128\*256. 

This is because, if we strictly follow the NoP of the third layer as 3\*256\*128, the third layer of OS-CNN would be wired. Normally, for CNN, the relationship of **number_of_Input_channle** and the **number_of_output_channle** should be same or one is 2 or 4 times of the other. If we strictly follow the NoP, the relationship might be 60 times.

For example, the NoP of OS-CNN is calculated by this: (1+2)\***number_of_Input_channle**\***number_of_output_channle**. If the **number_of_Input_channle** is 20 and the **number_of_output_channle** will be 1280. 
 
We calculate the NoP for each layer would be: 
~~~
First layer = Average_kernel_size * output_channel_first_layer = 8 * 128

Second layer = Average_kernel_size * output_channel_first_layer * output_channel_second_layer 
             = 7 * 128 * 256

Third layer  = 3 * output_channel_second_layer * output_channel_first_layer 
             = 7 * 3 * 128 * 256 / Average_kernel_size << 1 * 128 * 256
~~~
In total, the model size will be a little bit smaller than FCN, and the output_channel of the second layer is about two times than input_channel .
</details>


#### 2.	Did you use this specific setting for all the UCR datasets or did you vary this hyperparameter?

Yes, OS-CNN's result of all the UCR datasets is obtained under this setting. I did not change it.
